# Generated by ChatGPT on 2026-04-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='llm_provider',
            field=models.CharField(
                blank=True,
                choices=[('openai', 'OpenAI'), ('gemini', 'Gemini'), ('none', 'Sin IA')],
                max_length=20,
                null=True,
                verbose_name='Proveedor LLM',
            ),
        ),
        migrations.AddField(
            model_name='conversation',
            name='selected_document_id',
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name='ID del documento seleccionado',
            ),
        ),
    ]
